name: krinry Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - profile
          - release
      
      output_type:
        description: 'Output type'
        required: true
        default: 'apk'
        type: choice
        options:
          - apk
          - appbundle
          - apk-split
      
      target_platform:
        description: 'Target platform (APK only)'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - android-arm64
          - android-arm
          - android-x64

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
      
      - name: Flutter version
        run: flutter --version
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build
        run: |
          BUILD_TYPE="${{ github.event.inputs.build_type }}"
          OUTPUT_TYPE="${{ github.event.inputs.output_type }}"
          TARGET_PLATFORM="${{ github.event.inputs.target_platform }}"
          
          echo "🔨 Build Configuration:"
          echo "  Type: $BUILD_TYPE"
          echo "  Output: $OUTPUT_TYPE"
          echo "  Platform: $TARGET_PLATFORM"
          echo ""
          
          # Build APK
          if [ "$OUTPUT_TYPE" = "apk" ]; then
            if [ "$TARGET_PLATFORM" != "all" ]; then
              echo "Building APK ($BUILD_TYPE) for $TARGET_PLATFORM..."
              flutter build apk --$BUILD_TYPE --target-platform $TARGET_PLATFORM
            else
              echo "Building APK ($BUILD_TYPE)..."
              flutter build apk --$BUILD_TYPE
            fi
          
          # Build APK split per ABI
          elif [ "$OUTPUT_TYPE" = "apk-split" ]; then
            echo "Building split APKs ($BUILD_TYPE)..."
            flutter build apk --$BUILD_TYPE --split-per-abi
          
          # Build App Bundle
          elif [ "$OUTPUT_TYPE" = "appbundle" ]; then
            echo "Building App Bundle ($BUILD_TYPE)..."
            flutter build appbundle --$BUILD_TYPE
          fi
      
      - name: Upload APK
        if: ${{ github.event.inputs.output_type == 'apk' || github.event.inputs.output_type == 'apk-split' }}
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.event.inputs.build_type }}-${{ github.event.inputs.output_type }}
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 7
      
      - name: Upload App Bundle
        if: ${{ github.event.inputs.output_type == 'appbundle' }}
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.event.inputs.build_type }}-${{ github.event.inputs.output_type }}
          path: build/app/outputs/bundle/*/*.aab
          retention-days: 7
