name: krinry Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
          - split

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
      
      - name: Flutter version
        run: flutter --version
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build APK
        run: |
          BUILD_TYPE="${{ github.event.inputs.build_type }}"
          
          if [ "$BUILD_TYPE" = "debug" ]; then
            echo "Building debug APK..."
            flutter build apk --debug
          elif [ "$BUILD_TYPE" = "split" ]; then
            echo "Building release split APKs..."
            flutter build apk --release --split-per-abi
          else
            echo "Building release APK..."
            flutter build apk --release
          fi
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ github.event.inputs.build_type }}
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 7
